/**
 * models/GrowthPlan.js — Learning Roadmap Mongoose Model
 *
 * WHAT THIS MODEL STORES:
 * Each student has at most ONE active growth plan (unique constraint on `user`).
 * The plan is structured as a week-by-week learning roadmap generated by:
 *   1. Django's growth_planner.py → deterministic week-based task allocation
 *   2. Optionally enriched by gemini.service.js → geminiGenerateGapRoadmap()
 *
 * HOW TASK COMPLETION IS PRESERVED ACROSS REGENERATIONS:
 * When a student regenerates their roadmap (e.g. after uploading a new resume),
 * growth.service.js merges completion state from the OLD plan into the NEW plan
 * by matching tasks on their `key` field. If a task with the same key exists in
 * both plans, its `completed` and `completedAt` are carried over.
 *
 * KEY FIELD STABILITY:
 * The `key` field (e.g. "node-js", "gap-task-docker") must be STABLE across
 * regenerations for the merge to work. Django's growth_planner.py uses
 * skill names normalized to kebab-case for gap tasks, and week+index for
 * general curriculum tasks.
 *
 * PRIORITY LEVELS:
 * Each task has a priority level that drives UI styling in ExecutionEnginePage:
 * - 'core': The most critical skills — shown with amber accent bar
 * - 'recommended': Important but not blocking — shown with brand green bar
 * - 'supporting': Nice-to-have — shown with neutral bar
 *
 * UPSERT PATTERN (used in growth.service.js):
 * GrowthPlan.findOneAndUpdate(
 *   { user: userId },
 *   { $set: { targetRole, weeks, ... } },
 *   { upsert: true, new: true }
 * )
 * upsert: true creates the document if it doesn't exist (first-time generation)
 * and updates it if it does (subsequent regenerations).
 */

import mongoose from 'mongoose';

const { Schema } = mongoose;

/**
 * One learning task within a week.
 * Tasks are the atomic unit of progress — students mark them done via the
 * PATCH /api/growth/tasks/:key endpoint.
 *
 * { _id: false } — Tasks are identified by `key`, not MongoDB ObjectId,
 * so we don't need a separate _id for each one.
 */
const taskSchema = new Schema(
  {
    // Stable string identifier for this task — used to:
    //   1. Match tasks across regenerations (preserve completion)
    //   2. Route the PATCH /api/growth/tasks/:key toggle endpoint
    // Format: 'react' (skill name) or 'gap-task-docker' (gap-specific task)
    key: { type: String, required: true },

    // The skill this task focuses on (e.g. 'React', 'Docker', 'System Design')
    skill: String,

    // Human-readable task title
    // (e.g. 'Master React Hooks & Context API')
    title: String,

    // How important this task is relative to the student's gaps:
    // 'core' > 'recommended' > 'supporting'
    // This drives sort order and visual emphasis in the flight-strip UI
    priority: { type: String, enum: ['core', 'recommended', 'supporting'], default: 'core' },

    // Difficulty level (e.g. 'Beginner', 'Intermediate', 'Advanced')
    // Shown as a badge in the task card
    difficulty: { type: String, default: 'Beginner' },

    // Estimated hours to complete this task (used in week.focusHours total)
    estimatedHours: { type: Number, default: 0 },

    // Whether the student has marked this task as done
    completed: { type: Boolean, default: false },

    // Timestamp of when it was completed — used for progress timeline visualization
    completedAt: { type: Date, default: null },
  },
  { _id: false }
);

/**
 * One week in the roadmap.
 * A growth plan typically has 8–12 weeks organized by theme.
 *
 * { _id: false } — Weeks are accessed by index (week number), not ObjectId.
 */
const weekSchema = new Schema(
  {
    // Week number (1-indexed, e.g. 1, 2, 3...)
    // Displayed as a zero-padded badge in the flight-strip UI ('01', '02', ...)
    week: Number,

    // Theme for this week (e.g. 'Foundation & Core JavaScript', 'React Deep Dive')
    title: String,

    // Total estimated hours for all tasks in this week (sum of task.estimatedHours)
    focusHours: Number,

    // Array of tasks for this week (see taskSchema above)
    tasks: { type: [taskSchema], default: [] },
  },
  { _id: false }
);

/**
 * Main GrowthPlan schema — the `growthplans` collection in MongoDB.
 *
 * UNIQUENESS: unique: true on `user` enforces one plan per student.
 * If a student generates a new plan, it replaces the existing one (upsert).
 */
const growthPlanSchema = new Schema(
  {
    // Reference to the student this plan belongs to
    // unique: true enforces a strict 1:1 relationship (one plan per user)
    user: { type: Schema.Types.ObjectId, ref: 'User', required: true, unique: true, index: true },

    // The target role this roadmap is built for (e.g. 'Full Stack Developer')
    // Must match user.profile.dreamRole at generation time
    targetRole: { type: String, required: true },

    // Introductory summary paragraph shown at the top of the roadmap page
    // Generated by Django's growth_planner.py or Gemini
    summary: { type: String, default: '' },

    // Percentage of skill gaps covered by this roadmap at generation time (0–100)
    // Used to show "this plan addresses X% of your gaps" in the UI
    coverageStart: { type: Number, default: 0 },

    // ── Computed totals (derived from weeks[] for quick rendering) ─────────────

    // Total number of weeks in the roadmap
    totalWeeks: { type: Number, default: 0 },

    // Total number of tasks across all weeks
    totalTasks: { type: Number, default: 0 },

    // Total estimated hours to complete all tasks (sum of all week.focusHours)
    totalHours: { type: Number, default: 0 },

    // Skill areas the student is already strong in (from gap analysis)
    // Shown as "You're already good at:" in the UI
    strengths: { type: [String], default: [] },

    // The week-by-week roadmap data
    weeks: { type: [weekSchema], default: [] },
  },
  { timestamps: true } // createdAt = when first generated, updatedAt = last regeneration
);

export const GrowthPlan = mongoose.model('GrowthPlan', growthPlanSchema);
