/**
 * models/InterviewSession.js — AI Mock Interview Session Mongoose Model
 *
 * WHAT THIS MODEL STORES:
 * Each document is one completed mock interview session.
 * Sessions are 1:N with users — a student can complete many interview sessions
 * over time, and each one is preserved for historical analysis.
 *
 * HOW SESSIONS ARE CREATED:
 * 1. Student selects a gap from their gap analysis on InterviewPrepPage.jsx
 * 2. Client calls POST /api/ai-coach/interview/question → Gemini generates Q
 * 3. Student answers → POST /api/ai-coach/interview/evaluate → Gemini scores A
 * 4. Steps 2-3 repeat for each question in the session
 * 5. Student ends session → POST /api/ai-coach/interview/save-session
 *    → Creates this document with all questions and answers
 *
 * HOW SESSIONS ARE USED:
 * - insights.service.js reads sessions to compute average interview scores
 * - pathScore.service.js uses session count and average score in the Path Score
 * - report.controller.js includes recent sessions in the Career Report
 * - GET /api/ai-coach/interview/sessions returns history to InterviewPrepPage
 *
 * QUESTION RESULT SCHEMA:
 * Each question in the session has full rubric data from Gemini:
 * - totalScore: 0–100 numerical score
 * - grade: 'A', 'B', 'C', 'D' letter grade
 * - strengths: what the answer did well
 * - improvements: what to work on
 * - modelAnswer: Gemini's ideal answer for comparison
 * - timeTakenSeconds: how long the student took to answer (from timer)
 */

import mongoose from 'mongoose';

const { Schema } = mongoose;

/**
 * One evaluated question-answer pair in a session.
 *
 * { _id: false } — Questions are accessed by index within questions[],
 * not by individual MongoDB ObjectId. No separate _id needed.
 */
const questionResultSchema = new Schema(
  {
    // The interview question generated by Gemini
    // (e.g. 'Explain the difference between REST and GraphQL')
    question: { type: String, required: true },

    // The student's answer (transcribed from voice or typed)
    answer: { type: String, default: '' },

    // Which skill gap this question targeted
    // (e.g. 'System Design') — used in gap coverage reporting
    gapAddressed: { type: String, default: '' },

    // Gemini's numeric score for this answer (0–100)
    // Computed by geminiEvaluateAnswer() using a structured rubric prompt
    totalScore: { type: Number, default: 0 },

    // Letter grade corresponding to totalScore (e.g. 'A', 'B+', 'C')
    grade: { type: String, default: '' },

    // What the student's answer did well (array of positive feedback points)
    strengths: { type: [String], default: [] },

    // Areas to improve in future answers (array of feedback points)
    improvements: { type: [String], default: [] },

    // Gemini's ideal answer — shown to the student so they can learn the expected standard
    modelAnswer: { type: String, default: '' },

    // Time taken to answer in seconds (tracked by the countdown timer in InterviewPrepPage)
    timeTakenSeconds: { type: Number, default: 0 },
  },
  { _id: false }
);

/**
 * Main InterviewSession schema — the `interviewsessions` collection in MongoDB.
 */
const interviewSessionSchema = new Schema(
  {
    // The student this session belongs to
    user: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true },

    // The role being practiced for (matches user.profile.dreamRole at session start)
    targetRole: { type: String, required: true },

    // List of skill gaps that were addressed in this session
    // (subset of the student's keyGaps from resume analysis)
    gapsAddressed: { type: [String], default: [] },

    // All questions and evaluated answers in this session (1 to N items)
    questions: { type: [questionResultSchema], default: [] },

    // Count of questions in the session (denormalized for quick stats queries)
    totalQuestions: { type: Number, default: 0 },

    // Mean score across all questions in this session (0–100)
    // Pre-computed when the session is saved (avoids re-computing on every read)
    averageScore: { type: Number, default: 0 },

    // When the session was completed (used to sort sessions by recency)
    completedAt: { type: Date, default: Date.now },
  },
  { timestamps: true } // createdAt = session saved, updatedAt = rarely changes
);

export const InterviewSession = mongoose.model('InterviewSession', interviewSessionSchema);
