/**
 * models/JobMarketSnapshot.js — Job Market Intelligence Mongoose Model
 *
 * WHAT THIS MODEL STORES:
 * Weekly snapshots of skill demand and salary ranges for different roles,
 * derived from real job listings fetched via the Adzuna API.
 *
 * ONE ROW = one (role, skill, weekOf) combination.
 * Example row: { role: 'Full Stack Developer', skill: 'React', frequency: 78, weekOf: 2026-07-21 }
 * → "In the week of July 21, 78% of Full Stack Developer job postings mentioned React"
 *
 * HOW DATA GETS HERE:
 * 1. jobMarketCron.js runs weekly (or manually via POST /api/job-market/refresh)
 * 2. jobMarket.service.js calls the Adzuna API with a role-based query
 * 3. It extracts skills from job descriptions and calculates frequency %
 * 4. Results are upserted into this collection via bulkWrite with upsert:true
 *    (the unique index prevents duplicate rows if the cron runs twice in a week)
 *
 * HOW DATA IS USED:
 * - GET /api/job-market/:role → returns top skills by frequency for that role
 *   → Used in TalentAnalyzerPage Market tab and gap analysis prioritization
 * - GET /api/job-market/:role/salary → returns salary range for the role
 *   → Used in OverviewPage salary projection card
 *
 * SEED FALLBACK:
 * If the Adzuna API is not configured (no API keys), the job market service falls
 * back to static mock data generated by scripts/seed.js. This ensures the UI
 * has meaningful data even in development without API credentials.
 *
 * INDEXING STRATEGY:
 * - { role: 1, weekOf: -1 }: Fast lookup of "all skills for this role, newest first"
 * - { role: 1, skill: 1, weekOf: 1 } (unique): Prevents duplicate inserts on re-runs
 */

import mongoose from 'mongoose';

const { Schema } = mongoose;

/**
 * Main JobMarketSnapshot schema — the `jobmarketsnapshots` collection in MongoDB.
 *
 * These documents are NEVER updated — only upserted (new row per week).
 * Historical rows accumulate, enabling trend analysis over time.
 */
const jobMarketSnapshotSchema = new Schema(
  {
    // Target job role (e.g. 'Full Stack Developer', 'Data Scientist')
    // Normalized to consistent casing by jobMarket.service.js before storage
    role: {
      type: String,
      required: true,
      trim: true,
      index: true, // Indexed for role-based queries
    },

    // The skill mentioned in job postings (e.g. 'React', 'PostgreSQL', 'Docker')
    // Normalized to canonical form (e.g. 'node.js' → 'Node.js') before storage
    skill: {
      type: String,
      required: true,
      trim: true,
    },

    // Percentage of job postings for this role that mention this skill (0–100)
    // Example: 78 means 78% of Full Stack job listings require React this week
    // Used to rank skills by market demand and prioritize learning roadmap
    frequency: {
      type: Number,
      required: true,
      min: 0,
      max: 100,
    },

    // Salary range from job listings for this role (in INR Lakhs Per Annum)
    // min and max are averages across all listings that included salary data
    // null means no salary data was available from the listings
    avgSalaryRange: {
      min: { type: Number, default: null }, // e.g. 8 (means 8 LPA)
      max: { type: Number, default: null }, // e.g. 18 (means 18 LPA)
    },

    // Number of job listings analyzed to derive this snapshot row
    // Larger sample sizes = more reliable frequency percentages
    sampleSize: {
      type: Number,
      default: 0,
    },

    // The Monday of the ISO week this snapshot was collected.
    // All snapshots from the same weekly run share the same weekOf date.
    // Used to query the latest snapshot: .sort({ weekOf: -1 }).limit(N)
    weekOf: {
      type: Date,
      required: true,
      index: true,
    },
  },
  { timestamps: true }
);

// ── Indexes ────────────────────────────────────────────────────────────────────

// Compound index: "Get all skills for a role sorted by newest week"
// Used in: GET /api/job-market/:role → jobMarket.service.js
jobMarketSnapshotSchema.index({ role: 1, weekOf: -1 });

// Unique compound index: prevents inserting duplicate (role, skill, week) rows
// if the cron job runs more than once in the same week (idempotent upserts)
jobMarketSnapshotSchema.index({ role: 1, skill: 1, weekOf: 1 }, { unique: true });

export const JobMarketSnapshot = mongoose.model('JobMarketSnapshot', jobMarketSnapshotSchema);
